language: node_js
node_js: 
  - 10.13.0
addons:
  apt:
    update: true
cache:
  directories:
  - node_modules
install:
- npm install
before_script: 
script:
- hexo g
after_script:
- cd ./public
- git init
- git config user.name "JQ_Chan"
- git config user.email "vikers28@icloud.com"
- git add .
- git commit -m "Update site"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
branches:
  only:
  - dev
