language: node_js
node_js: stable

# Travis CI建议加的，自动更新api
addons: 
  apt:
    update: true

# Travis-CI Caching
cache:
  directories:
    - node_modules # 缓存 node_modules

# S: Build Lifecycle
install:
  - npm install # 初次安装，在CI环境中，执行安装npm依赖

before_script:
 # - npm install -g gulp


script:
  - hexo g # 执行 hexo generate，把文章编译到public中


after_script: # 执行script成功后，进入到public，把里面的代码提交到博客的gh-pages分支
  - cd ./public
  - git init
  - git config user.name "JQ_Chan"
  - git config user.email "vikers28@icloud.com"
  - git add .
  - git commit -m "Update site"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - dev # CI 只针对分支 dev
env:
 global: # 全局变量，上面的提交到github的命令有用到
   - GH_REF: github.com/jqchan/jqchan.github.io.git